pipeline {
    agent {
        docker {
            image 'container-registry.oracle.com/os/oraclelinux:9-slim'
            args '--userns=keep-id'
        }
    }

    stages {
        stage('Test') {
            steps {
                sh '''
                    id
                    uname -r
                    cat /etc/os-release
                '''
            }
        }
    }
}
